# Generated by Django 4.1.2 on 2022-10-15 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_password_user_passwd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='access',
            field=models.BooleanField(),
        ),
    ]
